title: blog.relativt.net
description: Eirik's public note to self
show_downloads: false
theme: jekyll-theme-hacker
google_analytics: UA-65597520-1
collections:
  posts:
    output: true
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
